# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_usuario2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class tela_usuario(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(781, 562)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 781, 571))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 255);\n"
"}\n"
"QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.img_logo = QtWidgets.QLabel(self.frame)
        self.img_logo.setGeometry(QtCore.QRect(30, 20, 151, 161))
        self.img_logo.setText("")
        self.img_logo.setPixmap(QtGui.QPixmap("img/LOGO.png"))
        self.img_logo.setScaledContents(True)
        self.img_logo.setObjectName("img_logo")
        self.text_segun = QtWidgets.QLabel(self.frame)
        self.text_segun.setGeometry(QtCore.QRect(220, 120, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.text_segun.setFont(font)
        self.text_segun.setObjectName("text_segun")
        self.text_hospital = QtWidgets.QLabel(self.frame)
        self.text_hospital.setGeometry(QtCore.QRect(180, 70, 581, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.text_hospital.setFont(font)
        self.text_hospital.setObjectName("text_hospital")
        self.text_usuario = QtWidgets.QLabel(self.frame)
        self.text_usuario.setGeometry(QtCore.QRect(180, 260, 91, 21))
        self.text_usuario.setObjectName("text_usuario")
        self.text_senha = QtWidgets.QLabel(self.frame)
        self.text_senha.setGeometry(QtCore.QRect(200, 320, 71, 20))
        self.text_senha.setObjectName("text_senha")
        self.botao_entrar = QtWidgets.QPushButton(self.frame)
        self.botao_entrar.setGeometry(QtCore.QRect(320, 430, 181, 41))
        self.botao_entrar.setObjectName("botao_entrar")
        self.lineEdit_usuario = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_usuario.setGeometry(QtCore.QRect(280, 260, 431, 22))
        self.lineEdit_usuario.setObjectName("lineEdit_usuario")
        self.lineEdit_senha = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_senha.setGeometry(QtCore.QRect(280, 320, 251, 22))
        self.lineEdit_senha.setObjectName("lineEdit_senha")
        self.img_usuario = QtWidgets.QLabel(self.frame)
        self.img_usuario.setGeometry(QtCore.QRect(20, 200, 171, 191))
        self.img_usuario.setText("")
        self.img_usuario.setPixmap(QtGui.QPixmap("img/medico.png"))
        self.img_usuario.setScaledContents(True)
        self.img_usuario.setObjectName("img_usuario")
        self.img_logo.raise_()
        self.text_segun.raise_()
        self.text_hospital.raise_()
        self.botao_entrar.raise_()
        self.lineEdit_usuario.raise_()
        self.lineEdit_senha.raise_()
        self.img_usuario.raise_()
        self.text_usuario.raise_()
        self.text_senha.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistema de Pacientes"))
        self.text_segun.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">SALVANDO VIDAS À 20 ANOS</span></p></body></html>"))
        self.text_hospital.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">HOSPITAL JOÃO AMOÊDO</span></p></body></html>"))
        self.text_usuario.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#000000;\">Usúario:</span></p></body></html>"))
        self.text_senha.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#000000;\">Senha:</span></p></body></html>"))
        self.botao_entrar.setText(_translate("MainWindow", "Entrar"))
        self.botao_entrar.clicked.connect(self.login)

    def abrir_tela_principal(self):
        from Tela_principal2 import tela_principal
        self.aba = QtWidgets.QMainWindow()
        self.abrir = tela_principal()
        self.abrir.setupUi(self.aba, pacientes, consultas, cirurgias)
        self.aba.show()


    def login(self):
        usuario = self.lineEdit_usuario.text()
        senha = self.lineEdit_senha.text()

        if usuario == "Doutor Wallison" and senha == "1234":
            self.abrir_tela_principal()
        else:
            QtWidgets.QMessageBox.information(None, "Erro", "Usuário ou senha incorretos. Tente novamente!")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = tela_usuario()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
