# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tela_principal2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class tela_principal(object):
    def setupUi(self, MainWindow, pacientes, consultas, cirurgias):
        self.cirurgias = cirurgias
        self.consultas = consultas
        self.pacientes = pacientes
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1134, 697)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(True)
        MainWindow.setTabletTracking(True)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QPushButton{\n"
"background-color: rgb(48, 172, 255);\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 291, 701))
        self.frame.setStyleSheet("background-color: rgb(67, 217, 231);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.botao_paciente = QtWidgets.QPushButton(self.frame)
        self.botao_paciente.setGeometry(QtCore.QRect(70, 250, 151, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.botao_paciente.setFont(font)
        self.botao_paciente.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/paciente.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_paciente.setIcon(icon)
        self.botao_paciente.setIconSize(QtCore.QSize(25, 25))
        self.botao_paciente.setAutoExclusive(False)
        self.botao_paciente.setObjectName("botao_paciente")
        self.botao_consultas = QtWidgets.QPushButton(self.frame)
        self.botao_consultas.setGeometry(QtCore.QRect(70, 350, 151, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.botao_consultas.setFont(font)
        self.botao_consultas.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/paciente (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_consultas.setIcon(icon1)
        self.botao_consultas.setIconSize(QtCore.QSize(25, 25))
        self.botao_consultas.setObjectName("botao_consultas")
        self.botao_cirurgia = QtWidgets.QPushButton(self.frame)
        self.botao_cirurgia.setGeometry(QtCore.QRect(70, 460, 151, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.botao_cirurgia.setFont(font)
        self.botao_cirurgia.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/cirurgia.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_cirurgia.setIcon(icon2)
        self.botao_cirurgia.setIconSize(QtCore.QSize(25, 25))
        self.botao_cirurgia.setObjectName("botao_cirurgia")
        self.botao_listar = QtWidgets.QPushButton(self.frame)
        self.botao_listar.setGeometry(QtCore.QRect(70, 580, 151, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.botao_listar.setFont(font)
        self.botao_listar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/relatorio-de-saude.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_listar.setIcon(icon3)
        self.botao_listar.setIconSize(QtCore.QSize(25, 25))
        self.botao_listar.setObjectName("botao_listar")
        self.linha = QtWidgets.QFrame(self.frame)
        self.linha.setGeometry(QtCore.QRect(280, -40, 20, 751))
        self.linha.setFrameShape(QtWidgets.QFrame.VLine)
        self.linha.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.linha.setObjectName("linha")
        self.img_equipe = QtWidgets.QLabel(self.frame)
        self.img_equipe.setGeometry(QtCore.QRect(40, 30, 191, 171))
        self.img_equipe.setText("")
        self.img_equipe.setPixmap(QtGui.QPixmap("img/equipe-medica.png"))
        self.img_equipe.setScaledContents(True)
        self.img_equipe.setObjectName("img_equipe")
        self.botao_consultas.raise_()
        self.botao_cirurgia.raise_()
        self.botao_listar.raise_()
        self.linha.raise_()
        self.img_equipe.raise_()
        self.botao_paciente.raise_()
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(290, -10, 851, 731))
        self.frame_2.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.texto_prontuario = QtWidgets.QLabel(self.frame_2)
        self.texto_prontuario.setGeometry(QtCore.QRect(210, 340, 431, 61))
        self.texto_prontuario.setObjectName("texto_prontuario")
        self.texto_eletronico = QtWidgets.QLabel(self.frame_2)
        self.texto_eletronico.setGeometry(QtCore.QRect(270, 400, 321, 61))
        self.texto_eletronico.setObjectName("texto_eletronico")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 40, 841, 201))
        self.frame_3.setStyleSheet("background-color: rgb(67, 217, 231);\n"
"background-color: rgb(0, 0, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.texto_hospital = QtWidgets.QLabel(self.frame_3)
        self.texto_hospital.setGeometry(QtCore.QRect(230, 40, 581, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.texto_hospital.setFont(font)
        self.texto_hospital.setObjectName("texto_hospital")
        self.text_segun = QtWidgets.QLabel(self.frame_3)
        self.text_segun.setGeometry(QtCore.QRect(260, 100, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.text_segun.setFont(font)
        self.text_segun.setObjectName("text_segun")
        self.img_logo = QtWidgets.QLabel(self.frame_3)
        self.img_logo.setGeometry(QtCore.QRect(30, -40, 211, 221))
        self.img_logo.setText("")
        self.img_logo.setPixmap(QtGui.QPixmap("img/LOGO.png"))
        self.img_logo.setScaledContents(True)
        self.img_logo.setObjectName("img_logo")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Prontúario Eletrônico"))
        self.botao_paciente.setText(_translate("MainWindow", " Pacientes"))
        self.botao_consultas.setText(_translate("MainWindow", " Consultas"))
        self.botao_cirurgia.setText(_translate("MainWindow", "  Cirurgia"))
        self.botao_listar.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.botao_listar.setText(_translate("MainWindow", " Listar"))
        self.frame_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.texto_prontuario.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; color:#ffffff;\">PRONTÚARIO</span></p></body></html>"))
        self.texto_eletronico.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:28pt; font-weight:600; color:#ffffff;\">ELETRÔNICO</span></p></body></html>"))
        self.texto_hospital.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">HOSPITAL JOÃO AMOÊDO</span></p></body></html>"))
        self.text_segun.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">SALVANDO VIDAS À 20 ANOS</span></p></body></html>"))
        self.botao_paciente.clicked.connect(self.abrir_cadastrar_pacientes)
        self.botao_consultas.clicked.connect(self.abrir_agenda_consultas)
        self.botao_cirurgia.clicked.connect(self.abrir_agenda_cirurgia)
        self.botao_listar.clicked.connect(self.abrir_tela_listar)


    def abrir_cadastrar_pacientes(self):
        from Tela_cadastrar_paciente import tela_cadastrar_paciente
        self.aba = QtWidgets.QMainWindow()
        self.abrir = tela_cadastrar_paciente()
        self.abrir.setupUi(self.aba, self.pacientes)
        self.aba.show()

    def abrir_tela_listar(self):
        from Tela_Listar import tela_listar
        self.aba = QtWidgets.QMainWindow()
        self.abrir = tela_listar()
        self.abrir.setupUi(self.aba, self.pacientes, self.consultas, self.cirurgias)
        self.aba.show()

    def abrir_agenda_consultas(self):
        from Tela_Agenda_consultar import tela_agenda_consultar
        self.aba = QtWidgets.QMainWindow()
        self.abrir = tela_agenda_consultar()
        self.abrir.setupUi(self.aba, self.consultas)
        self.aba.show()

    def abrir_agenda_cirurgia(self):
        from Tela_Agenda_cirurgia import tela_agenda_cirurgia
        self.aba = QtWidgets.QMainWindow()
        self.abrir = tela_agenda_cirurgia()
        self.abrir.setupUi(self.aba, self.cirurgias)
        self.aba.show()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pacientes = []
    consultas = []
    cirurgias = []

    MainWindow = QtWidgets.QMainWindow()
    ui = tela_principal()
    ui.setupUi(MainWindow, pacientes, consultas, cirurgias)

    MainWindow.show()
    sys.exit(app.exec_())
